---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iaas-core
  namespace: kubeiaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iaas-core
  template:
    metadata:
      labels:
        app: iaas-core
    spec:
      nodeSelector:
        kubeiaas/ctl: "true"
      containers:
        - name: iaas-core
          command: ["sh"]
          args:
            - "-c"
            - |
              java -jar /root/iaas-core.jar
          image: registry.cn-beijing.aliyuncs.com/kubeiaas/iaas-core:0.1.1-SNAPSHOT
          # -------- change to IfNotPresent when prod
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
              # -------- comment when prod
              hostPort: 9080
              protocol: TCP
          env:
            # -------- BASIC ENV --------
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # -------- SERVICE CONFIG --------
            - name: IAAS_CORE_NODE_NAME
              valueFrom:
                configMapKeyRef:
                  name: iaas-config
                  key: nodes.control
            - name: DB_PROXY_NODE_NAME
              valueFrom:
                configMapKeyRef:
                  name: iaas-config
                  key: nodes.control
            - name: RS_OPT_NODE_NAME
              valueFrom:
                configMapKeyRef:
                  name: iaas-config
                  key: nodes.control
            - name: IMG_OPT_NODE_NAME
              valueFrom:
                configMapKeyRef:
                  name: iaas-config
                  key: nodes.image
            - name: AGENT_NODE_NAME_LIST
              valueFrom:
                configMapKeyRef:
                  name: iaas-config
                  key: nodes.work.list
            - name: DHCP_NODE_NAME
              valueFrom:
                configMapKeyRef:
                  name: iaas-config
                  key: nodes.dhcp
            - name: VNC_NODE_NAME
              valueFrom:
                configMapKeyRef:
                  name: iaas-config
                  key: nodes.vnc
            - name: NFS_IP
              valueFrom:
                configMapKeyRef:
                  name: iaas-config
                  key: nodes.nfs
            # ----------------------------------
---
apiVersion: v1
kind: Service
metadata:
  name: iaas-core
  namespace: kubeiaas
spec:
  selector:
    app: iaas-core
  type: ClusterIP
  ports:
    - port: 9080
      targetPort: 9080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-proxy
  namespace: kubeiaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-proxy
  template:
    metadata:
      labels:
        app: db-proxy
    spec:
      nodeSelector:
        kubeiaas/ctl: "true"
      containers:
        - name: db-proxy
          image: registry.cn-beijing.aliyuncs.com/kubeiaas/db-proxy:0.1.1-SNAPSHOT-sqlite
          # -------- change to IfNotPresent when prod
          imagePullPolicy: Always
          ports:
            - containerPort: 9091
              protocol: TCP
          env:
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: sqlite-data
              mountPath: /db
      volumes:
        - name: sqlite-data
          hostPath:
            path: /usr/local/kubeiaas/sqlite
---
apiVersion: v1
kind: Service
metadata:
  name: db-proxy
  namespace: kubeiaas
spec:
  selector:
    app: db-proxy
  type: ClusterIP
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlite-tunnel
  namespace: kubeiaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlite-tunnel
  template:
    metadata:
      labels:
        app: sqlite-tunnel
    spec:
      nodeSelector:
        kubeiaas/ctl: "true"
      containers:
        - name: sqlite-tunnel
          image: free4inno/sqlite-tunnel:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8011
              # -------- comment when prod
              hostPort: 8011
              protocol: TCP
          volumeMounts:
            - name: sqlite-db
              mountPath: /db
      volumes:
        - name: sqlite-db
          hostPath:
            path: /usr/local/kubeiaas/sqlite
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iaas-agent
  namespace: kubeiaas
spec:
  selector:
    matchLabels:
      app: iaas-agent
  template:
    metadata:
      labels:
        app: iaas-agent
    spec:
      nodeSelector:
        kubeiaas/node: "true"
      hostPID: true
      hostIPC: true
      initContainers:
        - name: iaas-prepare
          image: registry.cn-beijing.aliyuncs.com/kubeiaas/iaas-prepare:0.1
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            # -------- BASIC ENV --------
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # -------- SERVICE CONFIG --------
            - name: DHCP_NODE
              valueFrom:
                configMapKeyRef:
                  name: iaas-config
                  key: nodes.dhcp
            - name: NFS_NODE
              valueFrom:
                configMapKeyRef:
                  name: iaas-config
                  key: nodes.nfs
            - name: NFS_DIR_IMG
              valueFrom:
                configMapKeyRef:
                  name: iaas-config
                  key: nfs.dir.img
            - name: NFS_DIR_DV
              valueFrom:
                configMapKeyRef:
                  name: iaas-config
                  key: nfs.dir.dv
            # ----------------------------------
          volumeMounts:
            - name: host-proc
              mountPath: /host/proc
            - name: checker
              mountPath: /checker
      containers:
        - name: iaas-agent
          command: ["sh"]
          args:
            - "-c"
            - |
              /bin/bash /kubeiaas/RUN.sh
          image: registry.cn-beijing.aliyuncs.com/kubeiaas/iaas-agent:0.1.1-SNAPSHOT
          # -------- change to IfNotPresent when prod
          imagePullPolicy: Always
          securityContext:
            privileged: true
          ports:
            - containerPort: 9090
              protocol: TCP
            - containerPort: 9089
              protocol: TCP
          env:
            # -------- BASIC ENV --------
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # -------- SERVICE CONFIG --------
            - name: DHCP_NODE
              valueFrom:
                configMapKeyRef:
                  name: iaas-config
                  key: nodes.dhcp
            - name: VNC_NODE
              valueFrom:
                configMapKeyRef:
                  name: iaas-config
                  key: nodes.vnc
            - name: NFS_NODE
              valueFrom:
                configMapKeyRef:
                  name: iaas-config
                  key: nodes.nfs
            # -------- NETWORK CONFIG --------
            - name: NETWORK_BRIDGE_TYPE
              valueFrom:
                configMapKeyRef:
                  name: iaas-config
                  key: network.bridge.type
            # ----------------------------------
          volumeMounts:
            - name: host-proc
              mountPath: /host/proc
            - name: workdir
              mountPath: /workdir
      volumes:
        - name: host-proc
          hostPath:
            path: /proc
        - name: checker
          hostPath:
            path: /usr/local/kubeiaas/workdir/checker
        - name: workdir
          hostPath:
            path: /usr/local/kubeiaas/workdir
---
apiVersion: v1
kind: Service
metadata:
  name: iaas-agent
  namespace: kubeiaas
spec:
  selector:
    app: iaas-agent
  type: NodePort
  ports:
    - port: 9090
      nodePort: 32301
      targetPort: 9090
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iaas-novnc
  namespace: kubeiaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iaas-novnc
  template:
    metadata:
      labels:
        app: iaas-novnc
    spec:
      nodeSelector:
        kubeiaas/vnc: "true"
      containers:
        - name: iaas-novnc
          command: [ "sh" ]
          args:
            - "-c"
            - |
              python3 /usr/local/vnc/websockify-0.10.0/websockify --web=/usr/local/vnc/noVNC-1.3.0/ 8787 --target-config=/usr/local/vnc/token/token.conf
          image: registry.cn-beijing.aliyuncs.com/kubeiaas/novnc:1.3.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8787
          volumeMounts:
            - name: novnc-token
              mountPath: /usr/local/vnc/token
      volumes:
        - name: novnc-token
          hostPath:
            path: /usr/local/kubeiaas/vnc/token
---
apiVersion: v1
kind: Service
metadata:
  name: iaas-novnc
  namespace: kubeiaas
spec:
  selector:
    app: iaas-novnc
  type: NodePort
  ports:
    - port: 8787
      nodePort: 32302
      targetPort: 8787
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-operator
  namespace: kubeiaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-operator
  template:
    metadata:
      labels:
        app: image-operator
    spec:
      nodeSelector:
        kubeiaas/img: "true"
      containers:
        - name: image-operator
          command: ["sh"]
          args:
            - "-c"
            - |
              java -jar /root/image-operator.jar
          image: registry.cn-beijing.aliyuncs.com/kubeiaas/image-operator:0.1.1-SNAPSHOT
          # -------- change to IfNotPresent when prod
          imagePullPolicy: Always
          ports:
            - containerPort: 9093
              protocol: TCP
          env:
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: host-image
              mountPath: /host-images
      volumes:
        - name: host-image
          hostPath:
            path: /usr/local/kubeiaas/data/images
---
apiVersion: v1
kind: Service
metadata:
  name: image-operator
  namespace: kubeiaas
spec:
  selector:
    app: image-operator
  type: ClusterIP
  ports:
    - port: 9093
      targetPort: 9093
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-operator
  namespace: kubeiaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-operator
  template:
    metadata:
      labels:
        app: resource-operator
    spec:
      nodeSelector:
        kubeiaas/ctl: "true"
      containers:
        - name: resource-operator
          command: ["sh"]
          args:
            - "-c"
            - |
              java -jar /root/resource-operator.jar
          image: registry.cn-beijing.aliyuncs.com/kubeiaas/resource-operator:0.1.1-SNAPSHOT
          # -------- change to IfNotPresent when prod
          imagePullPolicy: Always
          ports:
            - containerPort: 9092
              protocol: TCP
          env:
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: resource-operator
  namespace: kubeiaas
spec:
  selector:
    app: resource-operator
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
---