---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iaas-prepare
  namespace: kubeiaas
spec:
  selector:
    matchLabels:
      app: iaas-prepare
  template:
    metadata:
      labels:
        app: iaas-prepare
    spec:
      restartPolicy: Always
      nodeSelector:
        kubeiaas/node: "true"
      containers:
        - name: iaas-prepare
          image: registry.cn-beijing.aliyuncs.com/kubeiaas/iaas-prepare:0.1
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            # -------- BASIC ENV --------
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # -------- SERVICE CONFIG --------
            - name: DHCP_NODE
              valueFrom:
               configMapKeyRef:
                 name: iaas-config
                 key: nodes.dhcp
            - name: NFS_NODE
              valueFrom:
               configMapKeyRef:
                 name: iaas-config
                 key: nodes.nfs
            - name: NFS_DIR_IMG
              valueFrom:
                configMapKeyRef:
                  name: iaas-config
                  key: nfs.dir.img
            - name: NFS_DIR_DV
              valueFrom:
                configMapKeyRef:
                  name: iaas-config
                  key: nfs.dir.dv
            # ----------------------------------
          volumeMounts:
            - name: host-proc
              mountPath: /host/proc
            - name: checker
              mountPath: /checker
      volumes:
        - name: host-proc
          hostPath:
            path: /proc
        - name: checker
          hostPath:
            path: /usr/local/kubeiaas/workdir/checker